import { getRepoClient, parseRepoFullName } from "./GithubClient";
import { AIDiagnosis } from "@aiops/types";

export interface PRResult {
  prUrl: string;
  prNumber: number;
  branchName: string;
}

export async function createFixPR(
  repoFullName: string,
  incidentId: string,
  diagnosis: AIDiagnosis,
  fixDiff: string
): Promise<PRResult | null> {
  if (process.env.MOCK_DB === "true" || !process.env.GITHUB_APP_ID) {
    console.log(`[PRCreator][MOCK] Bypassing Git branch/PR creation for repository ${repoFullName}. Incident: ${incidentId}`);
    return {
      prUrl: `https://github.com/${repoFullName}/pull/42`,
      prNumber: 42,
      branchName: `aiops-fix/${incidentId.slice(0, 8)}-mock`
    };
  }

  if (!fixDiff || fixDiff.trim().length < 10) {
    console.log("[PRCreator] No valid diff provided, skipping PR creation");
    return null;
  }

  const { owner, repo } = parseRepoFullName(repoFullName);
  const octokit = await getRepoClient(owner, repo);

  // Get default branch
  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  // Get latest commit SHA from default branch
  const { data: refData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  const latestSha = refData.object.sha;

  // Create new branch
  const branchName = `aiops-fix/${incidentId.slice(0, 8)}-${Date.now()}`;
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: latestSha,
  });

  // Parse diff and apply file changes
  const filesToChange = parseDiffToFiles(fixDiff);

  for (const file of filesToChange) {
    try {
      // Get current file content + SHA
      let currentSha: string | undefined;
      try {
        const { data: fileData } = await octokit.rest.repos.getContent({
          owner,
          repo,
          path: file.path,
          ref: branchName,
        });
        if (!Array.isArray(fileData) && fileData.type === "file") {
          currentSha = fileData.sha;
        }
      } catch {
        // File doesn't exist yet — will be created
      }

      // Commit the file change
      await octokit.rest.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: file.path,
        message: `fix: ${diagnosis.rootCause.slice(0, 72)} [AIOps]`,
        content: Buffer.from(file.content).toString("base64"),
        branch: branchName,
        sha: currentSha,
      });
    } catch (err) {
      console.error(`[PRCreator] Failed to commit file ${file.path}:`, err);
    }
  }

  // Create the Pull Request
  const prBody = buildPRBody(incidentId, diagnosis);
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `🤖 [AIOps] Fix: ${diagnosis.rootCause.slice(0, 60)}`,
    body: prBody,
    head: branchName,
    base: defaultBranch,
  });

  // Add labels
  try {
    await octokit.rest.issues.addLabels({
      owner,
      repo,
      issue_number: pr.number,
      labels: ["aiops-fix", `risk:${diagnosis.riskLevel}`, "automated"],
    });
  } catch {
    // Labels may not exist, non-fatal
  }

  console.log(`[PRCreator] PR created: ${pr.html_url}`);

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branchName,
  };
}

// ─── Parse unified diff to file changes ──────────────────────────────────────

function parseDiffToFiles(diff: string): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];
  const fileBlocks = diff.split(/^diff --git/m).filter(Boolean);

  for (const block of fileBlocks) {
    const pathMatch = block.match(/b\/(.+)/);
    if (!pathMatch) continue;

    const filePath = pathMatch[1].split("\n")[0].trim();
    const lines = block.split("\n");
    const contentLines: string[] = [];

    let inHunk = false;
    for (const line of lines) {
      if (line.startsWith("@@")) {
        inHunk = true;
        continue;
      }
      if (!inHunk) continue;
      if (line.startsWith("-")) continue; // removed line
      if (line.startsWith("+")) {
        contentLines.push(line.slice(1));
      } else if (line.startsWith(" ")) {
        contentLines.push(line.slice(1));
      }
    }

    if (contentLines.length > 0) {
      files.push({ path: filePath, content: contentLines.join("\n") });
    }
  }

  return files;
}

// ─── Build PR description ─────────────────────────────────────────────────────

function buildPRBody(incidentId: string, diagnosis: AIDiagnosis): string {
  return `## 🤖 AIOps Automated Fix

> This PR was automatically generated by the **AI Incident Response Platform**.

### 📋 Incident Details
- **Incident ID**: \`${incidentId}\`
- **Error Type**: \`${diagnosis.errorType}\`
- **Risk Level**: \`${diagnosis.riskLevel.toUpperCase()}\`
- **AI Confidence**: **${diagnosis.confidence}%**

### 🔍 Root Cause
${diagnosis.rootCause}

### 🔧 Proposed Resolution
${diagnosis.resolution}

${
  diagnosis.similarIncidents && diagnosis.similarIncidents.length > 0
    ? `### 📚 Similar Past Incidents Used as Context
${diagnosis.similarIncidents
  .map((s, i) => `${i + 1}. **${s.title}** (${s.similarity}% similarity, resolved ${s.successCount} times)`)
  .join("\n")}
`
    : ""
}

### ⚠️ Review Checklist
- [ ] Verified the fix addresses the root cause
- [ ] Tested locally or in a staging environment
- [ ] No unintended side effects

---
*Generated by AIOps Copilot | ${new Date().toISOString()}*
`;
}
